#!/usr/bin/env bash

# Script to create a GitHub index metadata file, and push a new commit if it changed


# Fail script if variables are undefined
set -u
: "${SPACCHETTIBOTTI_TOKEN?Need to set SPACCHETTIBOTTI_TOKEN}"

# Or if some command fails
set -e

echo "Pulling latest"

git checkout master && git pull --rebase && git checkout -B master origin/master

function push-commit-if-changes {
    git add metadataV1.json && \
    echo "Pushing new commit (maybe)" && \
    git commit -m "Update GitHub index file" && \
    git push --set-upstream origin master
}


spago-curator index-github-meta
push-commit-if-changes || true
